---

- name: Setup variables
  ansible.builtin.set_fact:
    app_name: "erdtree"
    binary_name: "erd"
    app_version: "v3.1.2"

- name: Set download_url variable
  ansible.builtin.set_fact:
    download_url: "https://github.com/solidiquis/erdtree/releases/download/{{ app_version }}/erd-{{ app_version }}-x86_64-unknown-linux-musl.tar.gz"

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: "Download and unarchive to temp folder: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ tempdir.path }}"
    remote_src: true

- name: Move the application to the correct location
  ansible.builtin.command:
    cmd: mv "{{ tempdir.path }}/{{ binary_name }}" "{{ ansible_user_dir }}/.local/bin/{{ binary_name }}"
    creates: "/{{ ansible_user_dir }}/.local/bin/{{ binary_name }}"

- name: Delete the temporary directory
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent

- name: "Ensure config directory exists: {{ app_name }}"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/{{ app_name }}"
    state: directory
    mode: '0755'

- name: "Add config file: {{ app_name }}"
  ansible.builtin.template:
    src: .erdtree.toml.j2
    dest: "{{ ansible_user_dir }}/.config/{{ app_name }}/.erdtree.toml"
    mode: '0755'

- name: "Update fish config - add aliases: {{ app_name }}"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.config/fish/config.fish"
    line: "    alias ls='erd --config ls'

      \    alias ll='erd --config ll'\n"
    insertafter: '^\s*# additional aliases'
