---

- name: "Download and unarchive to temporary directory: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz"
    dest: "{{ ansible_user_dir }}"
    remote_src: true

- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/nvim-linux64/bin/nvim"
    dest: "{{ ansible_user_dir }}/.local/bin/nvim"
    state: link

- name: Clone the LazyVim starter
  ansible.builtin.git:
    repo: 'https://github.com/LazyVim/starter.git'
    dest: "{{ ansible_user_dir }}/.config/nvim"
    clone: true
    update: true

- name: Remove the .git folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim/.git"
    state: absent
