---

- name: "Download and unarchive to temporary directory: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz"
    dest: "{{ ansible_user_dir }}"
    remote_src: true

- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/nvim-linux64/bin/nvim"
    dest: "{{ ansible_user_dir }}/.local/bin/nvim"
    state: link
