#!/usr/bin/env sh

set -o errexit

ANSIBLE_REPO_PATH="$HOME/ansible.$(date +%H%M%S)"
ANSIBLE_REPO_BRANCH=main
ANSIBLE_REPO_PLAYBOOK=bootstrap
ANSIBLE_REPO_URL=https://github.com/bradleyfrank/ansible.git
VAULT_ID="$HOME/.ansible/vault"

bootstrap_linux() {
  apt-get update
  apt-get install sudo

  # Check if we're not inside a Docker container
  if [ ! -f /.dockerenv ] && ! grep -q container= /proc/1/cgroup; then
    sudo systemctl stop packagekit
  fi

  # shellcheck disable=SC1091
  . /etc/os-release

  case "$NAME" in
    Fedora*)
      sudo dnf clean all
      sudo dnf makecache
      sudo dnf install -y python3 python3-devel python3-pip python3-wheel gcc git redhat-lsb-core
      echo 'root' | passwd --stdin root
      ;;
    Ubuntu)
      sudo apt-get clean
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip git lsb-release
      echo 'root:root' | chpasswd
      ;;
    *) exit 1 ;;
  esac
}

while getopts ':dg:' opt; do
  case "$opt" in
    d) ANSIBLE_REPO_PLAYBOOK=dotfiles ;;
    g) ANSIBLE_REPO_BRANCH="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

if [ "$ANSIBLE_REPO_PLAYBOOK" = bootstrap ]; then
  case $(uname -s) in
    Darwin) bootstrap_mac ;;
    Linux)  bootstrap_linux ;;
    *)      exit 1 ;;
  esac
fi

# git clone "$ANSIBLE_REPO_URL" "$ANSIBLE_REPO_PATH"
# cd "$ANSIBLE_REPO_PATH" >/dev/null
# git checkout "$ANSIBLE_REPO_BRANCH"

PATH="$(python3 -m site --user-base)/bin:${PATH}"; export PATH
python3 -m pip install --user virtualenv
virtualenv venv
#shellcheck disable=SC1091
. venv/bin/activate
pip install --requirement requirements.txt

cat << EOF > setup/extra-vars.yml
current_system: "$(uname -s)"
current_hostname: "$(hostname -s)"
current_email: "$(id -un)@$(uname -n)"
EOF

ANSIBLE_CONFIG=setup/setup.cfg ansible-playbook setup/site.yml --extra-vars "@setup/extra-vars.yml"

case $ANSIBLE_REPO_PLAYBOOK in
  bootstrap) ansible-playbook --vault-password-file "$VAULT_ID" --ask-become-pass playbooks/bootstrap.yml ;;
  dotfiles)  ansible-playbook --vault-password-file "$VAULT_ID" playbooks/dotfiles.yml ;;
esac
