---
- name: Setup my dev environment
- hosts: localhost
  vars_files:
    - vault.yml
  vars:
    download_dir: "{{ ansible_env.HOME }}/Downloads" # TODO: this should be in a /tmp folder
    install_dir: "{{ ansible_env.HOME }}/.local/bin"
    config_dir: "{{ ansible_env.HOME }}/.config"
    softwares:
      - name: "zoxide"
        url: "https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest"
        base_download_url: "https://github.com/ajeetdsouza/zoxide/releases/download/{version}/zoxide-{version_no_v}-{ansible_architecture}-unknown-linux-musl.tar.gz"
        init_required: true

      - name: "starship"
        url: "https://api.github.com/repos/starship/starship/releases/latest"
        base_download_url: "https://github.com/starship/starship/releases/download/{version}/starship-{ansible_architecture}-unknown-linux-musl.tar.gz"
        init_required: true

      - name: "zellij"
        url: "https://api.github.com/repos/zellij-org/zellij/releases/latest"
        base_download_url: "https://github.com/zellij-org/zellij/releases/download/{version}/zellij-{ansible_architecture}-unknown-linux-musl.tar.gz"
        init_required: false

      - name: "navi"
        url: "https://api.github.com/repos/denisidoro/navi/releases/latest"
        base_download_url: "https://github.com/denisidoro/navi/releases/download/{version}/navi-{version}-{ansible_architecture}-unknown-linux-musl.tar.gz"
        init_required: false

  tasks:
    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ download_dir }}"
        - "{{ install_dir }}"
        - "{{ config_dir }}"

    - name: Update shell configuration
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$PATH:{{ install_dir }}"'
        insertafter: EOF
      register: line_in_file

    - import_tasks: fish/setup.yml

    - include_tasks: setup_tools.yml
      loop: "{{ softwares }}"
      loop_control:
        loop_var: software

    # - include_tasks: nvim/setup.yml
    - include_tasks: fzf/setup.yml
