---

- name: Setup variables
  ansible.builtin.set_fact:
    app_name: "fd"
    app_version: "v8.7.0"

- name: Set download_url variable
  ansible.builtin.set_fact:
    download_url: "https://github.com/sharkdp/fd/releases/download/{{ app_version }}/{{ app_name }}-{{ app_version }}-x86_64-unknown-linux-musl.tar.gz"

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: "Download and unarchive to temp folder: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ tempdir.path }}"
    remote_src: true

- name: Move the application to the correct location
  ansible.builtin.command:
    cmd: mv "{{ tempdir.path }}/{{ app_name }}-{{ app_version }}-x86_64-unknown-linux-musl/{{ app_name }}" "{{ ansible_user_dir }}/.local/bin/{{ app_name }}"
    creates: "/{{ ansible_user_dir }}/.local/bin/{{ app_name }}"

- name: Delete the temporary directory
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent
