---

- name: Setup variables
  ansible.builtin.set_fact:
    app_name: "fzf"
    app_version: "0.42.0"

- name: Set download_url variable
  ansible.builtin.set_fact:
    download_url: "https://github.com/junegunn/fzf/releases/download/{{ app_version }}/{{ app_name }}-{{ app_version }}-linux_amd64.tar.gz"

- name: "Download and unarchive to temporary directory: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ ansible_user_dir }}/.local/bin"
    remote_src: true

# - name: "Update fish config - add init line: {{ app_name }}"
#   ansible.builtin.lineinfile:
#     path: "{{ ansible_user_dir }}/.config/fish/config.fish"
#     line: "    {{ app_name }} init fish | source"
#     insertafter: '^\s*# sourcing tools'
