---
- name: Copy Ansible Galaxy requirements
  ansible.builtin.copy:
    src: requirements.yml
    dest: "{{ ansible_user_dir }}/.ansible/requirements.yml"
    mode: 755

- name: Copy Ansible Galaxy roles requirements
  ansible.builtin.copy:
    src: requirements_roles.yml
    dest: "{{ ansible_user_dir }}/.ansible/requirements_roles.yml"
    mode: 755

- name: Install Ansible Galaxy COLLECTIONS
  community.general.ansible_galaxy_install:
    type: collection
    requirements_file: "{{ ansible_user_dir }}/.ansible/requirements.yml"
    force: true

- name: Install Ansible Galaxy ROLES
  community.general.ansible_galaxy_install:
    type: role
    requirements_file: "{{ ansible_user_dir }}/.ansible/requirements_roles.yml"
    force: true
