---

- name: Setup variables
  ansible.builtin.set_fact:
    app_name: "zoxide"
    app_version: "v0.9.1"

- name: Set download_url variable
  ansible.builtin.set_fact:
    download_url: "https://github.com/ajeetdsouza/zoxide/releases/download/{{ app_version }}/{{ app_name }}-{{ app_version | replace('v', '') }}-x86_64-unknown-linux-musl.tar.gz"

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: "Download and unarchive to temp folder: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ tempdir.path }}"
    remote_src: true

- name: Move the application to the correct location
  ansible.builtin.command:
    cmd: mv "{{ tempdir.path }}/{{ app_name }}" "{{ ansible_user_dir }}/.local/bin/{{ app_name }}"
    creates: "/{{ ansible_user_dir }}/.local/bin/{{ app_name }}"

- name: Delete the temporary directory
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent

- name: "Update fish config - add init line: {{ app_name }}"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.config/fish/config.fish"
    line: "    {{ app_name }} init fish | source"
    insertafter: '^\s*# sourcing tools'
