---

- name: "Setup variables"
  ansible.builtin.set_fact:
    app_name: "bat"
    app_version: "v0.23.0"

- name: Set download_url variable
  ansible.builtin.set_fact:
    download_url: "https://github.com/sharkdp/bat/releases/download/{{ app_version }}/{{ app_name }}-{{ app_version }}-x86_64-unknown-linux-musl.tar.gz"

- name: "Create a temporary directory"
  ansible.builtin.tempfile:
    state: directory
  register: tempdir

- name: "Download and unarchive to temp folder: {{ app_name }}"
  ansible.builtin.unarchive:
    src: "{{ download_url }}"
    dest: "{{ tempdir.path }}"
    remote_src: true

- name: "Move tool to the correct location: {{ app_name }}"
  ansible.builtin.command:
    cmd: mv "{{ tempdir.path }}/{{ app_name }}-{{ app_version }}-x86_64-unknown-linux-musl/{{ app_name }}" "{{ ansible_user_dir }}/.local/bin/{{ app_name }}"
    creates: "{{ ansible_user_dir }}/.local/bin/{{ app_name }}"

- name: "Delete the temporary directory"
  ansible.builtin.file:
    path: "{{ tempdir.path }}"
    state: absent

- name: Ensure bat config directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/bat"
    state: directory
    mode: "0755"

- name: "Copy dotfiles for {{ app_name }}"
  ansible.builtin.copy:
    src: dotfiles/.config/{{ app_name }}
    dest: "{{ ansible_user_dir }}/.config"
    mode: "0755"
  tags: dotfiles

- name: Install themes for bat
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/bat cache --build"
  changed_when: false
  tags: dotfiles
