---
- name: Install and configure dotfiles on localhost
  hosts: localhost

  roles:
    - role: fish
    - role: atuin
    - role: navi
    - role: starship
    - role: zoxide
    - role: erdtree
    - role: fzf
    - role: bat
    - role: zellij
    - role: nvim
    - role: fd-find

  tasks:

    - name: Include os-specific package tasks
      ansible.builtin.include_tasks: "tasks/bootstrap/packages/{{ ansible_distribution | lower }}.yml"
      tags: always
