---
- name: install-Debian | Require fish >= 3 on Debian >= 10
  ansible.builtin.fail:
    msg: Only fish >= 3 is supported on Debian >= 10
  when:
    - ansible_facts.distribution == 'Debian'
    - fish_release_version is version('3', '<')
    - ansible_facts.distribution_major_version is version('10', '>=')
  tags:
    - fish

- name: Ensure dependencies are present. (fish)
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Fetch fish repository key
  become: true
  ansible.builtin.uri:
    url: "https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key"
    return_content: true
  register: fish_repo_key

- name: Add fish repository key
  become: true
  ansible.builtin.apt_key:
    data: "{{ fish_repo_key.content }}"
    state: present

- name: Add fish repository
  become: true
  ansible.builtin.apt_repository:
    filename: shells_fish_release_3
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/ /"
    state: present
  tags:
    - fish

- name: Install fish
  become: true
  ansible.builtin.apt:
    name: fish
    allow_unauthenticated: yes
    state: latest
    cache_valid_time: 600
  tags:
    - fish
